version: '3.4'

services:

  blazorpatient:
    image: ${DOCKER_REGISTRY-}blazorpatient
    build:
      context: .
      dockerfile: src/BlazorPatient/Dockerfile
    ports:
     - "6000:80"
     - "6001:443"
    depends_on:
     - patientdemographics-api
     - patienthistory-api
    networks:
     - bridge

  patientdemographics-api:
    image: ${DOCKER_REGISTRY-}patientdemographics
    build:
      context: .
      dockerfile: src/PatientDemographics/Dockerfile
    ports:
     - "5000:80"
     - "5001:443"
    depends_on:
     - sqldata
    networks:
     - bridge

  patienthistory-api:
    image: ${DOCKER_REGISTRY-}patienthistory
    build:
      context: .
      dockerfile: src/PatientHistory/Dockerfile
    ports:
     - "5002:80"
     - "5003:443"
    depends_on:
     - mongo
    networks:
     - bridge

  patientassessment-api:
    image: ${DOCKER_REGISTRY-}patientassessment
    build:
      context: .
      dockerfile: src/PatientAssessment/Dockerfile
    ports:
     - "5004:80"
     - "5005:443"
    depends_on:
    - patientdemographics-api
    - patienthistory-api
    networks:
     - bridge

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
     - bridge

  sqldata:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
       - SA_PASSWORD=Passw@rd123!
       - ACCEPT_EULA=Y
    ports:
        - "5433:1434"
    networks:
     - bridge

networks:
  bridge: